version: '2.1'
services:
   wireguard:
     cap_add:
       - NET_ADMIN
       - SYS_MODULE
     image: linuxserver/wireguard
     container_name: wireguard
     ports:
       - "51820:51820/udp"
     volumes: 
       - /wireguard/config:/config
       - /lib/modules:/lib/modules
     environment:
       - PUID=1000
       - PGID=1000
       - TZ=Europe/London
       - SERVERPORT=51820
       - PEERS=2
       - INTERNAL_SUBNET=10.13.13.0
       - ALLOWEDIPS=10.13.13.0/24 
     sysctls:
       - net.ipv4.conf.all.src_valid_mark=1
     restart: "unless-stopped"
     entrypoint: /bin/bash -c "curl -O https://raw.githubusercontent.com/emrekaankocoglu/disposable-timemachine-docker/main/startup.sh && bash startup.sh"

